### ISSUE TITLE
Shuts down when loading sockets.

### ISSUE THREAD

**Issue by Ankron** [joaoescribano/UltimaPHP#10]
Shuts down when loading sockets... no error printed.
![image](https://cloud.githubusercontent.com/assets/13837174/14979014/fc4c8106-10dc-11e6-8fe1-77ab779b24f3.png)

**Comment by joaoescribano** [comment]
Ankron, what version of PHP and UltimaPHP u'r using?

I'll do some tests on the weekend as soon i get some free time!

**Comment by Ankron** [comment]
I downloaded the copy right before I added localization. It could be a problem with the code I added. php version is Version: 5.6.20. 

    On Tuesday, May 3, 2016 2:26 PM, João Escribano <notifications@github.com> wrote:
 

 Ankron, what version of PHP and UltimaPHP u'r using?I'll do some tests on the weekend as soon i get some free time!—

**Comment by joaoescribano** [comment]
Cool! im using now php 7.0 cuz the improvements done in performance is awesome!!!! try to use this version :)

**Comment by Ankron** [comment]
Ah, ok. I'll run that version next time I got to test it. 

    On Wednesday, May 4, 2016 1:32 PM, João Escribano <notifications@github.com> wrote:
 

 Cool! im using now php 7.0 cuz the improvements done in performance is awesome!!!! try to use this version :)—

**Comment by joaoescribano** [comment]
Ankron, i've made some changes on the project.. i'll back to work on it and i've basicly re-created the socket server again.... now it validates the packet and wait ultill the client send the full packet to the server before start process.
