### ISSUE TITLE
.tele command

### ISSUE THREAD

**Issue by joaoescribano** [joaoescribano/UltimaPHP#17]
Need to create the mapsize validation to ensure server wont try to render player outside the map boundaries.

**Comment by Mutilador** [comment]
@joaoescribano Não sei se é o que voce quer... mas eu fiz uma limitação do tamanho total do mapX.mul, o cara ainda pode ir para parte preta de uma dungeon, isso tudo bem?

**Comment by joaoescribano** [comment]
Isso mesmo! já ta pronto isso entao :) testei aqui :+1:
