### ISSUE TITLE
Item names

### ISSUE THREAD

**Issue by joaoescribano** [joaoescribano/UltimaPHP#21]
@Mutilador can u please check the logic at the items sniffer for RunUO to make item names be stored with spaces and all lowercase?

It will help us later :+1:

**Comment by Mutilador** [comment]
@joao meu inglês não é tão bom, mas vc quer q eu coloque todos os items com nome minúsculo e com espaço no $this->name ?

**Comment by joaoescribano** [comment]
Exato Maurício, eles estão grudados um.no outro, ai no shard sai tipo VikingSword e não Vikings Word.

Ai deixa tudo minúsculo que isso a gente controla na renderização dos itens.

**Comment by Mutilador** [comment]
@joaoescribano  problem resolved and pushed new script tools and items updated
