### ISSUE TITLE
Implement EquipRequest and DropRequest

### ISSUE THREAD

**Issue by Mutilador** [joaoescribano/UltimaPHP#22]
**English**
The 0x13 package has been added and collecting the data correctly, the EquipRequest functions have been created but it is blank to be implemented, the creation of the container in the player is missing. 

The DropRequest function is apparently implemented, but only needs to be tested when the EquipRequest function is ready.

**Portuguese**
Já foram adicionados o pacote 0x13 e coletando os dados corretamente, as funções EquipRequest foi criada porém está em branco para ser implementada, falta a criação do container no player. 

A função DropRequest aparentemente está implementada, falta apenas testar quando a função EquipRequest estiver pronta.

**Comment by joaoescribano** [comment]
Fixed this issue on last commit
