### ISSUE TITLE
Mac Os

### ISSUE THREAD

**Issue by pedrosoares** [joaoescribano/UltimaPHP#25]
Quem usa MacOs precisa rodar igual ao linux. Mas vale lembrar para verificar a versão primeiro.
php -v
se for maior que 7.0 ok, senão

brew tap homebrew/dupes
brew tap homebrew/versions
brew tap homebrew/homebrew-php
brew install php71

**Comment by joaoescribano** [comment]
Pedro, obrigado pela info!

Consegue me fazer um log de como iniciar o server no MAC? assim ja adiciono no readme.md e também crio uma página na WIKI para descrever como usar no mac :)

Valew

**Comment by joaoescribano** [comment]
@pedrosoares consegue nos ajudar nessa parte?

**Comment by pedrosoares** [comment]
Opa, claro, chegando em casa eu te mando o LOG.
