### ISSUE TITLE
Parse error: syntax error, unexpected '[' in G:\xampp\htdocs\uop\core\sockets.co

### ISSUE THREAD

**Issue by windofuo** [joaoescribano/UltimaPHP#7]
When i run it,i got the message below:
G:\xampp\php>php.exe G:\xampp\htdocs\uop\startsever.php
23:57:50: Starting server
23:57:50: Loading file: ultimaphp.ini
23:57:50: Loading file: core/functions.core.php
23:57:50: Loading file: core/packets.core.php
23:57:50: Loading file: core/sockets.core.php

Parse error: syntax error, unexpected '[' in G:\xampp\htdocs\uop\core\sockets.co
re.php on line 125

G:\xampp\php>

**Comment by windofuo** [comment]
Ok,the server run correctly after two files modified.
1, core\sockets.core.php,in line 125,it looks like this:
    $packet = unpack('H*', $compression->compress(strtoupper($packet))) [1];
and i changed it like blow:
    $prepacket = unpack('H*', $compression->compress(strtoupper($packet)));
    $packet = $prepacket[1];
not sure if it's the right way because im not good at scripting....but server error was gone...and the next one:
2, core\server.php there is four "SELF",change them into lowcase"self",now the server could run.

**Comment by joaoescribano** [comment]
1) It happens cuz your PHP version may be 5.3, right? this [1] was implemented on PHP 5.4 version.

2) Thanks!!!! you made it right!!!! please feel free to commit this code change!

**Comment by joaoescribano** [comment]
As you can see here: http://php.net/manual/pt_BR/migration54.new-features.php

**Comment by windofuo** [comment]
Yes,thank a lot for your guide firstly.My php version is exactly 5.3 and it bring the first one.
I realy don't understand any programming and so i had to solved it in my foolish way.haha!
Your UltimaPHP is so amazing.Wish you go on with it.I can't help with anything about programing but if there are a lot of manual labor,maybe i can help^-^.
I'm sorry for my English...
