### ISSUE TITLE
Working with UsbWebServer

### ISSUE THREAD

**Issue by cafoob** [joaoescribano/UltimaPHP#8]
Hi. First i'm glad to find your project. I was realy thinking about same. But i've a problem with sockets i think. Here is;

````16:39:18: Starting server 16:39:18: Loading file: ultimaphp.ini 16:39:18: Loading file: core/functions.core.php 16:39:18: Loading file: core/packets.core.php 16:39:18: Loading file: core/sockets.core.php 16:39:18: Server is listening on 127.0.0.1 at port 2593 16:39:18: Loading file: class/account.class.php 16:39:18: Loading file: class/baseObject.class.php 16:39:18: Loading file: class/compression.class.php 16:39:18: Loading file: class/encrypt.class.php 16:39:18: Loading file: class/player.class.php 16:39:18: Trying to connect to the database 16:39:20 (DANGER) : Server could not connect to the database with error: SQLSTATE[HY000] [2002] Hedef makine etkin olarak reddetti�inden ba�lant� kurulamad�. 16:39:20: Stoping server````

How can i fix that? Have you any idea about that? Thank you so much.

**Comment by joaoescribano** [comment]
We fixed this error editing php.ini and seting to enable the extensions: PDO, Sockets
